name: Deploy no Kubernetes
on:
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
      images:
        type: string
        required: true

      environment:
        type: string
        required: true
        description: "Nome do ambiente utilizado"

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
          kubectl apply -f ${{ inputs.manifests }} -n ${{ inputs.environment }}
          kubectl set image deployment/web web=${{ inputs.images }} -n ${{ inputs.environment }}
          echo "Aplicação implantada com sucesso no ambiente ${{ inputs.environment }} e com a versao da imagem ${{ inputs.images }}"
