name: Deploy no Kubernetes
on:
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
      images:
        type: string
        required: true

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
          kubectl create namespace webserver || echo "Namespace criado"
          kubectl apply -f ${{ inputs.manifests }} -n webserver
